
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "e0web"
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "6700:3306"
    hostname: "db"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
    links:
      - "db"

  web:
    image: eboraas/apache-php
    ports:
      - "6070:80"
    volumes:
      - "./10web:/var/www/html"
    links:
      - "db"
    restart: "always"

